version: 2

updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "weekly"
            day: "monday"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/columns-layout"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/rows-layout"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/masonry-layout"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/custom-renderers"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/playground"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/sortable-gallery"
        schedule:
            interval: "monthly"
            time: "10:00"
            timezone: "America/New_York"
