version: 2

updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "daily"
            time: "10:00"
            timezone: "America/New_York"

    -   package-ecosystem: "npm"
        directory: "/examples/columns-layout"
        schedule:
            interval: "weekly"
            day: "monday"
            time: "10:00"
            timezone: "America/New_York"
