blank_issues_enabled: false
contact_links:
    -   name: Question
        url: https://github.com/igordanchenko/react-photo-album/discussions/categories/q-a
        about: Please post questions under the Q&A category in Discussions
