name: CI

on: [ push ]

jobs:
    build:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: [ '12.x', '14.x', '16.x', '17.x' ]
                os: [ ubuntu-latest, windows-latest, macOS-latest ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup Node.js ${{ matrix.node }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node }}

            -   name: Install dependencies
                uses: bahmutov/npm-install@v1

            -   name: Lint
                run: npm run lint

            -   name: Test
                run: npm run test

            -   name: Build
                run: npm run build
